sudo: false
language: node_js
cache: yarn
node_js:
  - "8"
before_script:
  - rm -rf ./coverage
install:
  - yarn global add codecov
  - yarn
script:
  - yarn build
  - NODE_ENV=test ./node_modules/.bin/jest --env=jsdom --coverage
  - codecov
