sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
  - "6"
before_script:
  - rm -r -f ./coverage
install:
  - yarn global add codecov
script:
  - yarn build
after_script:
  - NODE_ENV=test ./node_modules/.bin/jest --env=jsdom --coverage --updateSnapshot
  - codecov
